Lesson11
mariyamurashova/Test-Guru pull request #17
Opened 2023-07-17 00:36 UTC by mariyamurashova

1. Реализована аутентификации в проекте при помощи библиотеки Devise
2. Сделано управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализовано перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратор назначается  автором теста

При регистрации пользователя запрашивается его имя и фамилия и после входа, выводится флэш-сообщение "Привет, <имя пользователя>!"

2023-07-17 08:05 UTC, BubuntuClu requested changes

2023-07-17 08:05 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +   redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `current_user.admin?`

2023-07-17 08:05 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +     params.require(:test).permit(:title, :level, :category_id, :author_id)
автора отсюда надо убрать

2023-07-17 08:05 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
>. При создании нового теста администратором назначайте его в качестве автора теста

тут надо подставлять пользователя, не из параметров

2023-07-17 08:05 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
почему используешь `current_user` а не пришедшего `user`? есть разница в них? какой правильный в итоге?

2023-07-17 08:05 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>  class QuestionsController < ApplicationController
нужны ли еще контроллеры вопросов и ответов вне неймспейса админа? что на них может делать пользователь?

2023-07-17 08:05 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +  def index
список вопросов отображается на странице теста. по идеи этот экшн уже давно не используется

2023-07-18 21:02 UTC, mariyamurashova commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
current_user и user  - объект пользователя текущей сессии, по-моему разницы нет,  логичней использовать user

2023-07-18 21:10 UTC, mariyamurashova commented on app/controllers/admin/tests_controller.rb
> +     params.require(:test).permit(:title, :level, :category_id, :author_id)
пробовала сделать так @test=current_user.tests.create(test_params), но в этом случае :author_id  - nil.

2023-07-19 09:22 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +     params.require(:test).permit(:title, :level, :category_id, :author_id)
разве ассоциация `tests` отвечает за созданные тесты? нет, другая, ее и надо испльзовать

2023-07-19 09:23 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test.author_id = current_user.id
не, это костыль. https://github.com/mariyamurashova/Test-Guru/pull/17#discussion_r1267810352 вот тут коммент. надо использовать другую ассоциацию

2023-07-19 10:27 UTC, merged